# Generated by Django 2.2.4 on 2019-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_server', models.CharField(max_length=100)),
                ('ldap_port', models.IntegerField()),
                ('ldap_user', models.CharField(max_length=100)),
                ('ldap_password', models.CharField(max_length=100)),
                ('ldap_use_tls', models.BooleanField(max_length=100)),
                ('ldap_user_filter', models.CharField(max_length=1000)),
                ('ldap_group_filter', models.CharField(max_length=1000)),
            ],
        ),
    ]
