# Generated by Django 3.0.2 on 2020-02-01 21:08

import django.core.files.storage
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0002_ldapsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('street', models.CharField(default=None, max_length=40)),
                ('number', models.CharField(default=None, max_length=5)),
                ('zipcode', models.CharField(default=None, max_length=5)),
                ('city', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('tax_number', models.CharField(default=None, max_length=50)),
                ('register_number', models.CharField(default=None, max_length=50)),
                ('logo', models.FileField(blank=True, default=None, null=True,
                                          storage=django.core.files.storage.FileSystemStorage(
                                              location='/var/cypetulip'),
                                          upload_to=mediaserver.upload.public_files_upload_handler)),
            ],
        ),
    ]
