# Generated by Django 3.0.2 on 2020-02-01 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0003_legalsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LdapSettings',
            new_name='LdapSetting',
        ),
        migrations.RenameModel(
            old_name='LegalSettings',
            new_name='LegalSetting',
        ),
        migrations.RenameModel(
            old_name='MailSettings',
            new_name='MailSetting',
        ),
    ]
