# Generated by Django 3.0.2 on 2020-05-11 13:34

import django.core.files.storage
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0004_auto_20200201_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalsetting',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='/var/cypetulip/'),
                                   upload_to=mediaserver.upload.public_files_upload_handler),
        ),
    ]
