# Generated by Django 3.0.2 on 2020-05-13 10:07

import django.core.files.storage
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0005_auto_20200511_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalsetting',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='C:\\var\\cypetulip'),
                                   upload_to=mediaserver.upload.public_files_upload_handler),
        ),
    ]
