apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - env:
        - name: NGINX_HOST
          valueFrom:
            configMapKeyRef:
              key: NGINX_HOST
              name: packaging-nginx--env-nginx-prod
        - name: NGINX_PORT
          valueFrom:
            configMapKeyRef:
              key: NGINX_PORT
              name: packaging-nginx--env-nginx-prod
        image: nginx
        imagePullPolicy: ""
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/cypetulip/
          name: media-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-volume
status: {}
