# Generated by Django 3.0.2 on 2020-02-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200201_2208'),
        ('payment', '0002_auto_20200201_1348'),
    ]

    operations = [
    ]
