# Generated by Django 3.1.3 on 2021-03-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_migrate_order_to_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='order',
        ),
    ]
