# Generated by Django 3.0.2 on 2020-01-16 20:24

import django.core.files.storage
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='picture',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='/var/cypetulip/'),
                                   upload_to=mediaserver.upload.public_files_upload_handler),
        ),
    ]
