# Generated by Django 3.0.2 on 2020-01-15 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AppUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.App')),
            ],
        ),
        migrations.CreateModel(
            name='AppUrlPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_access', models.BooleanField(default=True)),
                ('get_access', models.BooleanField(default=True)),
                ('post_message', models.CharField(
                    default="You don't have the required permissions to do any changes in this view. If you think this is wrong please contact our support",
                    max_length=400)),
                ('get_message', models.CharField(
                    default="You don't have the required permissions to show this view. If you think this is wrong please contact our support",
                    max_length=400)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.AppUrl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_administrator', models.BooleanField(default=False)),
                ('is_shop_employee', models.BooleanField(default=False)),
                ('can_access_app', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
