# Generated by Django 3.1.3 on 2021-03-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_migrate_order_fields'),
        ('rma', '0003_auto_20210305_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnmerchandiseauthorization',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderdetail'),
        ),
    ]
