# Generated by Django 3.0.2 on 2020-01-10 19:33

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('term_of_payment', models.IntegerField()),
                ('street', models.CharField(default=None, max_length=40)),
                ('number', models.CharField(default=None, max_length=5)),
                ('zipcode', models.CharField(default=None, max_length=5)),
                ('city', models.CharField(default=None, max_length=30)),
                ('logo', models.FileField(blank=True, default=None, null=True,
                                          storage=django.core.files.storage.FileSystemStorage(
                                              location='/var/cypetulip'),
                                          upload_to=mediaserver.upload.company_files_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(default='en', max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Company')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('order_hash', models.CharField(blank=True, max_length=30, null=True)),
                ('is_send', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=25, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_text', models.CharField(blank=True, max_length=200, null=True)),
                ('count', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='shop.Employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='shop.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('special_price', models.FloatField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('details', models.CharField(max_length=300)),
                ('requires_file_upload', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_multiple_per_item', models.BooleanField(default=False)),
                ('is_once_per_order', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SelectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CheckBoxOrderItem',
            fields=[
                ('orderitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.OrderItem')),
                ('is_checked', models.BooleanField()),
            ],
            bases=('shop.orderitem',),
        ),
        migrations.CreateModel(
            name='CheckBoxSubItem',
            fields=[
                ('productsubitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.ProductSubItem')),
            ],
            bases=('shop.productsubitem',),
        ),
        migrations.CreateModel(
            name='FileOrderItem',
            fields=[
                ('orderitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.OrderItem')),
                ('file', models.FileField(default=None, null=True, storage=django.core.files.storage.FileSystemStorage(
                    location='/var/cypetulip'), upload_to=mediaserver.upload.order_files_upload_handler)),
                ('file_name', models.CharField(blank=True, max_length=40)),
            ],
            bases=('shop.orderitem',),
        ),
        migrations.CreateModel(
            name='FileSubItem',
            fields=[
                ('productsubitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.ProductSubItem')),
            ],
            bases=('shop.productsubitem',),
        ),
        migrations.CreateModel(
            name='NumberOrderItem',
            fields=[
                ('orderitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.OrderItem')),
                ('number', models.IntegerField()),
            ],
            bases=('shop.orderitem',),
        ),
        migrations.CreateModel(
            name='NumberSubItem',
            fields=[
                ('productsubitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.ProductSubItem')),
            ],
            bases=('shop.productsubitem',),
        ),
        migrations.CreateModel(
            name='SelectSubItem',
            fields=[
                ('productsubitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.ProductSubItem')),
            ],
            bases=('shop.productsubitem',),
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('is_main_category', models.BooleanField(default=False)),
                ('child_categories', models.ManyToManyField(blank=True, default=None, related_name='ChildCategories',
                                                            to='shop.ProductCategory')),
                ('mother_category',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='shop.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('initial', models.BooleanField(default=False)),
                ('next_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='previous_state', to='shop.OrderState')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('next_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='previous_state', to='shop.OrderItemState')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductSubItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='shop.OrderItemState'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_bill', models.DateTimeField(blank=True, null=True)),
                ('assigned_employee',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='shop.Employee')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Contact')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='shop.OrderState')),
            ],
        ),
        migrations.CreateModel(
            name='SelectOrderItem',
            fields=[
                ('orderitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.OrderItem')),
                ('selected_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SelectItem')),
            ],
            bases=('shop.orderitem',),
        ),
        migrations.AddField(
            model_name='selectitem',
            name='select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SelectSubItem'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productsubitem_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='shop.ProductSubItem')),
                ('product_picture', models.FileField(blank=True, default=None, null=True,
                                                     storage=django.core.files.storage.FileSystemStorage(
                                                         location='/var/cypetulip'),
                                                     upload_to=mediaserver.upload.public_files_upload_handler)),
                ('is_public', models.BooleanField()),
                ('assigned_sub_products', models.ManyToManyField(blank=True, default=None, related_name='sub_products',
                                                                 to='shop.ProductSubItem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductCategory')),
            ],
            bases=('shop.productsubitem',),
        ),
        migrations.CreateModel(
            name='FileExtensionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=30)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.FileSubItem')),
            ],
        ),
    ]
