# Generated by Django 3.0.2 on 2020-01-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_auto_20200115_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='shop.Address'),
        ),
        migrations.AddField(
            model_name='productsubitem',
            name='special_price',
            field=models.FloatField(default=False),
        ),
    ]
