# Generated by Django 3.1.3 on 2021-03-06 18:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_populate_uuid_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='individual_offer_request',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.individualoffer'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='session',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
