# Generated by Django 3.0.2 on 2020-01-16 20:24

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20200115_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='shop.Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='/var/cypetulip/'),
                                   upload_to=mediaserver.upload.company_files_upload_handler),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileorderitem',
            name='file',
            field=models.FileField(default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='/var/cypetulip/'),
                                   upload_to=mediaserver.upload.order_files_upload_handler),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='/var/cypetulip/'),
                                   upload_to=mediaserver.upload.public_files_upload_handler),
        ),
    ]
