# Generated by Django 3.1.3 on 2021-03-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_migrate_order_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
