# Generated by Django 3.0.2 on 2020-01-30 20:07

import django.core.files.storage
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004_auto_20200116_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='c:/var/cypetulip/'),
                                   upload_to=mediaserver.upload.company_files_upload_handler),
        ),
        migrations.AlterField(
            model_name='fileorderitem',
            name='file',
            field=models.FileField(default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='c:/var/cypetulip/'),
                                   upload_to=mediaserver.upload.order_files_upload_handler),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, default=None, null=True,
                                    storage=django.core.files.storage.FileSystemStorage(location='c:/var/cypetulip/'),
                                    upload_to=mediaserver.upload.public_files_upload_handler),
        ),
    ]
