# Generated by Django 3.0.2 on 2020-01-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0006_auto_20200130_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubitem',
            name='special_price',
            field=models.FloatField(blank=True, default=False, null=True),
        ),
    ]
