# Generated by Django 3.0.2 on 2020-02-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0008_auto_20200201_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_number',
            field=models.CharField(max_length=30),
        ),
    ]
