# Generated by Django 3.0.2 on 2020-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200201_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubitem',
            name='tax',
            field=models.FloatField(default=0.19),
        ),
    ]
