# Generated by Django 3.0.2 on 2020-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productsubitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
