# Generated by Django 3.0.2 on 2020-02-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderitem_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price',
            new_name='price',
        ),
    ]
