# Generated by Django 3.0.2 on 2020-02-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0009_auto_20200202_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstate',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
