# Generated by Django 3.0.2 on 2020-02-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200201_2104'),
        ('shop', '0008_auto_20200201_2208'),
    ]

    operations = [
    ]
