# Generated by Django 2.2.9 on 2020-02-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0013_auto_20200202_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='shipment_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='shop.Address'),
        ),
    ]
