# Generated by Django 3.0.2 on 2020-02-12 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0014_orderdetail_shipment_address'),
        ('shop', '0013_auto_20200201_2356'),
    ]

    operations = [
    ]
