# Generated by Django 3.0.2 on 2020-05-13 10:07

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0016_auto_20200511_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_de',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_en',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='contact_de',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='shop.Contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='contact_en',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='shop.Contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='number_de',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='number_en',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_de',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_en',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode_de',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode_en',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='C:\\var\\cypetulip'),
                                   upload_to=mediaserver.upload.company_files_upload_handler),
        ),
        migrations.AlterField(
            model_name='fileorderitem',
            name='file',
            field=models.FileField(default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='C:\\var\\cypetulip'),
                                   upload_to=mediaserver.upload.order_files_upload_handler),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, default=None, null=True,
                                    storage=django.core.files.storage.FileSystemStorage(location='C:\\var\\cypetulip'),
                                    upload_to=mediaserver.upload.public_files_upload_handler),
        ),
    ]
