# Generated by Django 3.0.2 on 2020-05-13 15:19

import django.core.files.storage
from django.db import migrations, models

import mediaserver.upload


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0017_auto_20200513_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city_de',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact_de',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact_en',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='address',
            name='number_de',
        ),
        migrations.RemoveField(
            model_name='address',
            name='number_en',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_de',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_en',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zipcode_de',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zipcode_en',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='/var/cypetulip'),
                                   upload_to=mediaserver.upload.company_files_upload_handler),
        ),
        migrations.AlterField(
            model_name='fileorderitem',
            name='file',
            field=models.FileField(default=None, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(location='/var/cypetulip'),
                                   upload_to=mediaserver.upload.order_files_upload_handler),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, default=None, null=True,
                                    storage=django.core.files.storage.FileSystemStorage(location='/var/cypetulip'),
                                    upload_to=mediaserver.upload.public_files_upload_handler),
        ),
    ]
