# Generated by Django 3.0.2 on 2020-05-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0018_auto_20200513_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='billing_address', to='shop.Address'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='shipment_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='shipment_address', to='shop.Address'),
        ),
    ]
